@startuml System

!pragma ratio 0.7
skinparam TitleFontSize 32
title Conference System

!include deps.puml

Person(speaker, "Speaker")
Person(organizer, "Organizer")
Person(atendee, "Atendee")

System(conference_system, "Conference System", "Mnagement system for running a conference")

System_Ext(email_system, "E-Mail System")
System_Ext(sms_system, "SMS System")
System_Ext(phone_system, "Phone System")

Rel(atendee, conference_system, "Views speaking schedule, rates talks, gets updates on schedule changes and views slides using")
Rel(organizer, conference_system, "Configures branding and registers schedule changes using")
Rel(speaker, conference_system, "Manages talks")

Rel(conference_system, email_system, "Sends e-mail using")
Rel(conference_system, sms_system, "Sends SMS using")
Rel(conference_system, phone_system, "Makes calls using")

Rel(email_system, atendee, "Sends e-mails to")
Rel(sms_system, atendee, "Sends SMS to")
Rel(phone_system, atendee, "Makes calls to")

@enduml
