name: Flask Container CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "devops/flask_container_ci/**"
      - '.github/workflows/**'


defaults:
  run:
    working-directory: devops/flask_container_ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        pytest

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        ./scripts/build.sh
    - name: Smoke test
      run: |
        python3 smoketest.py

