AWSTemplateFormatVersion: 2010-09-09

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: 's3:GetObject'
          Effect: Allow
          Principal: '*'
          Resource:
            - !Sub arn:aws:s3:::${WebsiteBucket}/*

Outputs:
  WebsiteURL:
    Value: !GetAtt
      - WebsiteBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  BucketName:
    Value: !GetAtt
      - WebsiteBucket
      - DomainName
    Description: Name of S3 bucket
